server:
  port: 8082
  
spring:
  profiles:
    active: local
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false 
    
mybatis:
  mapper-locations: sql/**/*.xml
  configuration:
    call-setters-on-nulls: true
    
---

spring:
  config:
    activate:
      on-profile:
      - local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://15.164.43.222:3306/sbuddy?serverTimezone=UTC&characterEncoding=UTF-8
    username: sbuddev
    password: sbuddev12#$
    
    
---

spring:
  config:
    activate:
      on-profile:
      - dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://15.164.43.222:3306/sbuddy?serverTimezone=UTC&characterEncoding=UTF-8
    username: sbuddev
    password: sbuddev12#$