server:
  port: 8082
  
spring:
  profiles:
    active: local
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false 
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  config:
    import: classpath:/aws.yml
    
mybatis:
  mapper-locations: sql/**/*.xml
  configuration:
    call-setters-on-nulls: true
        
cloud:
  aws:
    stack.auto: false
    region.static: ap-southeast-2
    s3:
      bucket: sbuddy-bucket
    
jwt:
  secret:
    key: b7c1ccf275440e551218989bb7ce9dd23485a7274ff5eaa95e3092626dc164e738b6120681b9abef7426c0be11ae2915f9bf4256293c3a7545ea129bdc6db8d6

---

spring:
  config:
    activate:
      on-profile:
      - local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://15.164.43.222:3306/sbuddy?serverTimezone=UTC&characterEncoding=UTF-8
    username: sbuddev
    password: sbuddev12#$
  mail:
    host: smtp.gmail.com
    port: 587
    username: leenomt@chungbuk.ac.kr
    password: xosw ujub yqpi notz
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
            
logging:
  config: classpath:log4j2_local.yml
    
    
---

spring:
  config:
    activate:
      on-profile:
      - dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://15.164.43.222:3306/sbuddy?serverTimezone=UTC&characterEncoding=UTF-8
    username: sbuddev
    password: sbuddev12#$
  mail:
    host: smtp.gmail.com
    port: 587
    username: leenomt@chungbuk.ac.kr
    password: xosw ujub yqpi notz
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
            
logging:
  config: classpath:log4j2_dev.yml