server:
  port: 8082
  
spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sbuddy?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    
    
mybatis:
  mapper-locations: sql/**/*.xml
  configuration:
    call-setters-on-nulls: true